### PR TITLE
Develop METS harness

### PR DESCRIPTION
**Pull request by ross-spencer**

### CODE REVIEW

**Comment by ross-spencer** [comment]
Whoops! Sorry, wrong repo! :slightly_smiling_face:

**Comment by dancaron** [comment]
Hey Ross, I'll take a look at these changes. Would love your contributions
if they are broadly applicable.

**Comment by dancaron** [comment]
Oh, it looks like changes are for a specific application?

**Comment by ross-spencer** [comment]
Yeah, sorry @dancaron one of those quirks when you assume because you've got your origin set straight your PR will land in the right place too. I wondered why my PR was #5! FWWI working with your code has been really straightforward and nothing spotted of issue so far to warrant a PR I think :slightly_smiling_face: Thank you for making this reference repo!

**Pull request closed without merging**
